from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets  import QMessageBox
import json
import requests
import subprocess as sp

url = "https://api.rootnet.in/covid19-in/stats/latest"
response = requests.get(url)
parsed=response.text
data=json.loads(parsed)


cc1=data['data']['summary']['total']
cci1=data['data']['summary']['confirmedCasesIndian']
ccf1=data['data']['summary']['confirmedCasesForeign']
recv1=data['data']['summary']['discharged']
dead1=data['data']['summary']['deaths']
active1=cc1-(recv1+dead1)

cc2=data['data']['unofficial-summary'][0]['total']
recv2=data['data']['unofficial-summary'][0]['recovered']
dead2=data['data']['unofficial-summary'][0]['deaths']
active2=data['data']['unofficial-summary'][0]['active']

st_list = ['Andaman and Nicobar Islands','Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chandigarh','Chhattisgarh','Dadar Nagar Haveli','Delhi','Goa',
           'Gujrat','Haryana','Himachal Pradesh','Jammu and Kashmir','Jharkhand','Karnataka','Kerala','Ladakh','Madhya Pradesh','Maharashtra','Manipur','Meghalaya',
           'Mizoram','Nagaland','Odisha','Puducherry','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telengana','Tripura','Uttarakhand','Uttar Pradesh','West Bengal']


class Ui_OfficialMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 648)
        MainWindow.setMinimumSize(QtCore.QSize(801, 648))
        MainWindow.setMaximumSize(QtCore.QSize(801, 648))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TITLE = QtWidgets.QLabel(self.centralwidget)
        self.TITLE.setGeometry(QtCore.QRect(0, -10, 801, 111))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(38)
        self.TITLE.setFont(font)
        self.TITLE.setStyleSheet("background-color: rgb(0, 0, 0);")
        
        self.TITLE.setObjectName("TITLE")
        self.TITLE2 = QtWidgets.QLabel(self.centralwidget)
        self.TITLE2.setGeometry(QtCore.QRect(130, 130, 591, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(32)
        self.TITLE2.setFont(font)
        self.TITLE2.setObjectName("TITLE2")
        
        self.confirmedcases = QtWidgets.QLabel(self.centralwidget)
        self.confirmedcases.setGeometry(QtCore.QRect(30, 240, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.confirmedcases.setFont(font)
        self.confirmedcases.setObjectName("confirmedcases")
        
        self.activecases = QtWidgets.QLabel(self.centralwidget)
        self.activecases.setGeometry(QtCore.QRect(430, 240, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.activecases.setFont(font)
        self.activecases.setObjectName("activecases")
        
        self.indianorigin = QtWidgets.QLabel(self.centralwidget)
        self.indianorigin.setGeometry(QtCore.QRect(30, 330, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.indianorigin.setFont(font)
        self.indianorigin.setObjectName("indianorigin")
        
        self.nonindianorigin = QtWidgets.QLabel(self.centralwidget)
        self.nonindianorigin.setGeometry(QtCore.QRect(420, 330, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.nonindianorigin.setFont(font)
        self.nonindianorigin.setObjectName("nonindianorigin")
        
        self.recovered = QtWidgets.QLabel(self.centralwidget)
        self.recovered.setGeometry(QtCore.QRect(30, 410, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.recovered.setFont(font)
        self.recovered.setObjectName("recovered")
        
        self.deaths = QtWidgets.QLabel(self.centralwidget)
        self.deaths.setGeometry(QtCore.QRect(420, 410, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.deaths.setFont(font)
        self.deaths.setObjectName("deaths")
        
        self.confirmedcasesdata = QtWidgets.QLabel(self.centralwidget)
        self.confirmedcasesdata.setGeometry(QtCore.QRect(280, 260, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.confirmedcasesdata.setFont(font)
        self.confirmedcasesdata.setFrameShape(QtWidgets.QFrame.Box)
        self.confirmedcasesdata.setAlignment(QtCore.Qt.AlignCenter)
        self.confirmedcasesdata.setObjectName("confirmedcasesdata")
        
        self.indianorigindata = QtWidgets.QLabel(self.centralwidget)
        self.indianorigindata.setGeometry(QtCore.QRect(230, 350, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.indianorigindata.setFont(font)
        self.indianorigindata.setFrameShape(QtWidgets.QFrame.Box)
        self.indianorigindata.setAlignment(QtCore.Qt.AlignCenter)
        self.indianorigindata.setObjectName("indianorigindata")
        
        self.recovereddata = QtWidgets.QLabel(self.centralwidget)
        self.recovereddata.setGeometry(QtCore.QRect(280, 430, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recovereddata.setFont(font)
        self.recovereddata.setFrameShape(QtWidgets.QFrame.Box)
        self.recovereddata.setAlignment(QtCore.Qt.AlignCenter)
        self.recovereddata.setObjectName("recovereddata")
        
        self.activecasesdata = QtWidgets.QLabel(self.centralwidget)
        self.activecasesdata.setGeometry(QtCore.QRect(630, 260, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.activecasesdata.setFont(font)
        self.activecasesdata.setFrameShape(QtWidgets.QFrame.Box)
        self.activecasesdata.setAlignment(QtCore.Qt.AlignCenter)
        self.activecasesdata.setObjectName("activecasesdata")
        
        self.nonindianorigindata = QtWidgets.QLabel(self.centralwidget)
        self.nonindianorigindata.setGeometry(QtCore.QRect(690, 350, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.nonindianorigindata.setFont(font)
        self.nonindianorigindata.setFrameShape(QtWidgets.QFrame.Box)
        self.nonindianorigindata.setAlignment(QtCore.Qt.AlignCenter)
        self.nonindianorigindata.setObjectName("nonindianorigindata")
        
        self.deathsdata = QtWidgets.QLabel(self.centralwidget)
        self.deathsdata.setGeometry(QtCore.QRect(550, 430, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.deathsdata.setFont(font)
        self.deathsdata.setFrameShape(QtWidgets.QFrame.Box)
        self.deathsdata.setAlignment(QtCore.Qt.AlignCenter)
        self.deathsdata.setObjectName("deathsdata")
        
        self.unofficialsrcs = QtWidgets.QPushButton(self.centralwidget)
        self.unofficialsrcs.clicked.connect(self.unoff_click)
        self.unofficialsrcs.setGeometry(QtCore.QRect(20, 490, 246, 81))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(16)
        self.unofficialsrcs.setFont(font)
        self.unofficialsrcs.setDefault(False)
        self.unofficialsrcs.setObjectName("unofficialsrcs")
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.clicked.connect(self.state_click)
        self.pushButton.setGeometry(QtCore.QRect(276, 490, 246, 81))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.countriesButton = QtWidgets.QPushButton(self.centralwidget)
        self.countriesButton.clicked.connect(self.country_click)
        self.countriesButton.setGeometry(QtCore.QRect(540, 490, 246, 81))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(18)
        self.countriesButton.setFont(font)
        self.countriesButton.setObjectName("countriesButton")
        
        self.version = QtWidgets.QLabel(self.centralwidget)
        self.version.setGeometry(QtCore.QRect(20, 600, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(12)
        font.setBold(True)
        self.version.setFont(font)
        self.version.setObjectName("version")
        
        self.refresh = QtWidgets.QLabel(self.centralwidget)
        self.refresh.setGeometry(QtCore.QRect(339, 600, 441, 20))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setBold(True)
        font.setPointSize(12)
        self.refresh.setFont(font)
        self.refresh.setObjectName("refresh")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 26))
        self.menubar.setObjectName("menubar")
        
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "COVID-19 Tracker By Avilash Ghosh"))
        self.TITLE.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic; color:#ffffff;\">COVID-19 Tracker By Avilash</span></p></body></html>"))
        self.TITLE2.setText(_translate("MainWindow", "Data from Govt of India:"))
        self.confirmedcases.setText(_translate("MainWindow", "Confirmed Cases: "))
        self.activecases.setText(_translate("MainWindow", "Active Cases: "))
        self.indianorigin.setText(_translate("MainWindow", "Indian Origin:"))
        self.nonindianorigin.setText(_translate("MainWindow", "Non-Indian Origin:"))
        self.recovered.setText(_translate("MainWindow", "Recovered Cases: "))
        self.deaths.setText(_translate("MainWindow", "Deaths: "))
        self.confirmedcasesdata.setText(_translate("MainWindow", str(cc1)))
        self.indianorigindata.setText(_translate("MainWindow", str(cci1)))
        self.recovereddata.setText(_translate("MainWindow", str(recv1)))
        self.activecasesdata.setText(_translate("MainWindow", str(active1)))
        self.nonindianorigindata.setText(_translate("MainWindow", str(ccf1)))
        self.deathsdata.setText(_translate("MainWindow", str(dead1)))
        self.unofficialsrcs.setText(_translate("MainWindow", "Data from \nCovid19.org"))
        self.pushButton.setText(_translate("MainWindow", "Data of \nIndividual States"))
        self.version.setText(_translate("MainWindow", "Version: 1.4"))
        self.refresh.setText("Last Refreshed on: "+str(data['lastRefreshed']))
        self.countriesButton.setText("Data of\nOther Countries")

    def unoff_click(self):
        OffMainWindow.close()
        UnoffMainWindow.show()
    
    def state_click(self):
        OffMainWindow.close()
        StateWindow.show()

    def country_click(self):
        OffMainWindow.close()
        CountryWindow.show()


class Ui_UnofficialMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 648)
        MainWindow.setMinimumSize(QtCore.QSize(801, 648))
        MainWindow.setMaximumSize(QtCore.QSize(801, 648))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TITLE = QtWidgets.QLabel(self.centralwidget)
        self.TITLE.setGeometry(QtCore.QRect(0, -10, 801, 111))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(38)
        self.TITLE.setFont(font)
        self.TITLE.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.TITLE.setObjectName("TITLE")
        
        self.TITLE2 = QtWidgets.QLabel(self.centralwidget)
        self.TITLE2.setGeometry(QtCore.QRect(130, 130, 591, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(32)
        self.TITLE2.setFont(font)
        self.TITLE2.setObjectName("TITLE2")
        
        self.confirmedcases = QtWidgets.QLabel(self.centralwidget)
        self.confirmedcases.setGeometry(QtCore.QRect(30, 290, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.confirmedcases.setFont(font)
        self.confirmedcases.setObjectName("confirmedcases")
        
        self.activecases = QtWidgets.QLabel(self.centralwidget)
        self.activecases.setGeometry(QtCore.QRect(420, 290, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.activecases.setFont(font)
        self.activecases.setObjectName("activecases")
        
        self.recovered = QtWidgets.QLabel(self.centralwidget)
        self.recovered.setGeometry(QtCore.QRect(20, 370, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.recovered.setFont(font)
        self.recovered.setObjectName("recovered")
        
        self.deaths = QtWidgets.QLabel(self.centralwidget)
        self.deaths.setGeometry(QtCore.QRect(410, 370, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.deaths.setFont(font)
        self.deaths.setObjectName("deaths")
        
        self.confirmedcasesdata = QtWidgets.QLabel(self.centralwidget)
        self.confirmedcasesdata.setGeometry(QtCore.QRect(280, 310, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.confirmedcasesdata.setFont(font)
        self.confirmedcasesdata.setFrameShape(QtWidgets.QFrame.Box)
        self.confirmedcasesdata.setAlignment(QtCore.Qt.AlignCenter)
        self.confirmedcasesdata.setObjectName("confirmedcasesdata")
        
        self.recovereddata = QtWidgets.QLabel(self.centralwidget)
        self.recovereddata.setGeometry(QtCore.QRect(280, 390, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recovereddata.setFont(font)
        self.recovereddata.setFrameShape(QtWidgets.QFrame.Box)
        self.recovereddata.setAlignment(QtCore.Qt.AlignCenter)
        self.recovereddata.setObjectName("recovereddata")
        
        self.activecasesdata = QtWidgets.QLabel(self.centralwidget)
        self.activecasesdata.setGeometry(QtCore.QRect(630, 310, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.activecasesdata.setFont(font)
        self.activecasesdata.setFrameShape(QtWidgets.QFrame.Box)
        self.activecasesdata.setAlignment(QtCore.Qt.AlignCenter)
        self.activecasesdata.setObjectName("activecasesdata")
        
        self.deathsdata = QtWidgets.QLabel(self.centralwidget)
        self.deathsdata.setGeometry(QtCore.QRect(550, 390, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.deathsdata.setFont(font)
        self.deathsdata.setFrameShape(QtWidgets.QFrame.Box)
        self.deathsdata.setAlignment(QtCore.Qt.AlignCenter)
        self.deathsdata.setObjectName("deathsdata")
        
        self.unofficialsrcs = QtWidgets.QPushButton(self.centralwidget)
        self.unofficialsrcs.clicked.connect(self.off_click)
        self.unofficialsrcs.setGeometry(QtCore.QRect(20, 490, 246, 81))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(16)
        self.unofficialsrcs.setFont(font)
        self.unofficialsrcs.setDefault(False)
        self.unofficialsrcs.setObjectName("unofficialsrcs")
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.clicked.connect(self.state_click)
        self.pushButton.setGeometry(QtCore.QRect(276, 490, 246, 81))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.countriesButton = QtWidgets.QPushButton(self.centralwidget)
        self.countriesButton.clicked.connect(self.country_click)
        self.countriesButton.setGeometry(QtCore.QRect(540, 490, 246, 81))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(18)
        self.countriesButton.setFont(font)
        self.countriesButton.setObjectName("countriesButton")
        
        self.version = QtWidgets.QLabel(self.centralwidget)
        self.version.setGeometry(QtCore.QRect(20, 600, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(12)
        font.setBold(True)
        self.version.setFont(font)
        self.version.setObjectName("version")
        
        self.refresh = QtWidgets.QLabel(self.centralwidget)
        self.refresh.setGeometry(QtCore.QRect(339, 600, 441, 20))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setBold(True)
        font.setPointSize(12)
        self.refresh.setFont(font)
        self.refresh.setObjectName("refresh")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 26))
        self.menubar.setObjectName("menubar")
        
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "COVID-19 Tracker By Avilash Ghosh"))
        self.TITLE.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic; color:#ffffff;\">COVID-19 Tracker By Avilash</span></p></body></html>"))
        self.TITLE2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Data from covid19.org:</p></body></html>"))
        self.confirmedcases.setText(_translate("MainWindow", "Confirmed Cases: "))
        self.activecases.setText(_translate("MainWindow", "Active Cases: "))
        self.recovered.setText(_translate("MainWindow", "Recovered Cases: "))
        self.deaths.setText(_translate("MainWindow", "Deaths: "))
        self.confirmedcasesdata.setText(_translate("MainWindow", str(cc2)))
        self.recovereddata.setText(_translate("MainWindow", str(recv2)))
        self.activecasesdata.setText(_translate("MainWindow", str(active2)))
        self.deathsdata.setText(_translate("MainWindow", str(dead2)))
        self.unofficialsrcs.setText(_translate("MainWindow", "Data from \nGovt of India"))
        self.pushButton.setText(_translate("MainWindow", "Data of \nIndividual States"))
        self.version.setText(_translate("MainWindow", "Version: 1.4"))
        self.refresh.setText("Last Refreshed on: "+str(data['lastRefreshed']))
        self.countriesButton.setText("Data of\nOther Countries")

    def off_click(self):
        UnoffMainWindow.close()
        OffMainWindow.show()

    def state_click(self):
        UnoffMainWindow.close()
        StateWindow.show()

    def country_click(self):
        UnoffMainWindow.close()
        CountryWindow.show()


class Ui_StateMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 648)
        MainWindow.setMinimumSize(QtCore.QSize(801, 648))
        MainWindow.setMaximumSize(QtCore.QSize(801, 648))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TITLE = QtWidgets.QLabel(self.centralwidget)
        self.TITLE.setGeometry(QtCore.QRect(0, -10, 801, 111))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(38)
        self.TITLE.setFont(font)
        self.TITLE.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.TITLE.setObjectName("TITLE")
        
        self.TITLE2 = QtWidgets.QLabel(self.centralwidget)
        self.TITLE2.setGeometry(QtCore.QRect(10, 130, 341, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(32)
        self.TITLE2.setFont(font)
        self.TITLE2.setObjectName("TITLE2")
        
        self.confirmedcases = QtWidgets.QLabel(self.centralwidget)
        self.confirmedcases.setGeometry(QtCore.QRect(30, 240, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.confirmedcases.setFont(font)
        self.confirmedcases.setObjectName("confirmedcases")
        
        self.activecases = QtWidgets.QLabel(self.centralwidget)
        self.activecases.setGeometry(QtCore.QRect(430, 240, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.activecases.setFont(font)
        self.activecases.setObjectName("activecases")
        
        self.indianorigin = QtWidgets.QLabel(self.centralwidget)
        self.indianorigin.setGeometry(QtCore.QRect(30, 330, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.indianorigin.setFont(font)
        self.indianorigin.setObjectName("indianorigin")
        
        self.nonindianorigin = QtWidgets.QLabel(self.centralwidget)
        self.nonindianorigin.setGeometry(QtCore.QRect(420, 330, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.nonindianorigin.setFont(font)
        self.nonindianorigin.setObjectName("nonindianorigin")
        
        self.recovered = QtWidgets.QLabel(self.centralwidget)
        self.recovered.setGeometry(QtCore.QRect(30, 410, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.recovered.setFont(font)
        self.recovered.setObjectName("recovered")
        
        self.deaths = QtWidgets.QLabel(self.centralwidget)
        self.deaths.setGeometry(QtCore.QRect(420, 410, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.deaths.setFont(font)
        self.deaths.setObjectName("deaths")
        
        self.confirmedcasesdata = QtWidgets.QLabel(self.centralwidget)
        self.confirmedcasesdata.setGeometry(QtCore.QRect(280, 260, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.confirmedcasesdata.setFont(font)
        self.confirmedcasesdata.setFrameShape(QtWidgets.QFrame.Box)
        self.confirmedcasesdata.setAlignment(QtCore.Qt.AlignCenter)
        self.confirmedcasesdata.setObjectName("confirmedcasesdata")
        
        self.indianorigindata = QtWidgets.QLabel(self.centralwidget)
        self.indianorigindata.setGeometry(QtCore.QRect(230, 350, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.indianorigindata.setFont(font)
        self.indianorigindata.setFrameShape(QtWidgets.QFrame.Box)
        self.indianorigindata.setAlignment(QtCore.Qt.AlignCenter)
        self.indianorigindata.setObjectName("indianorigindata")
        
        self.recovereddata = QtWidgets.QLabel(self.centralwidget)
        self.recovereddata.setGeometry(QtCore.QRect(280, 430, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recovereddata.setFont(font)
        self.recovereddata.setFrameShape(QtWidgets.QFrame.Box)
        self.recovereddata.setAlignment(QtCore.Qt.AlignCenter)
        self.recovereddata.setObjectName("recovereddata")
        
        self.activecasesdata = QtWidgets.QLabel(self.centralwidget)
        self.activecasesdata.setGeometry(QtCore.QRect(630, 260, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.activecasesdata.setFont(font)
        self.activecasesdata.setFrameShape(QtWidgets.QFrame.Box)
        self.activecasesdata.setAlignment(QtCore.Qt.AlignCenter)
        self.activecasesdata.setObjectName("activecasesdata")
        
        self.nonindianorigindata = QtWidgets.QLabel(self.centralwidget)
        self.nonindianorigindata.setGeometry(QtCore.QRect(690, 350, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.nonindianorigindata.setFont(font)
        self.nonindianorigindata.setFrameShape(QtWidgets.QFrame.Box)
        self.nonindianorigindata.setAlignment(QtCore.Qt.AlignCenter)
        self.nonindianorigindata.setObjectName("nonindianorigindata")
        
        self.deathsdata = QtWidgets.QLabel(self.centralwidget)
        self.deathsdata.setGeometry(QtCore.QRect(550, 430, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.deathsdata.setFont(font)
        self.deathsdata.setFrameShape(QtWidgets.QFrame.Box)
        self.deathsdata.setAlignment(QtCore.Qt.AlignCenter)
        self.deathsdata.setObjectName("deathsdata")
        
        self.unofficialsrcs = QtWidgets.QPushButton(self.centralwidget)
        self.unofficialsrcs.clicked.connect(self.unoff_click_st)
        self.unofficialsrcs.setGeometry(QtCore.QRect(276, 490, 246, 81))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(16)
        self.unofficialsrcs.setFont(font)
        self.unofficialsrcs.setDefault(False)
        self.unofficialsrcs.setObjectName("unofficialsrcs")
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.clicked.connect(self.off_click_st)
        self.pushButton.setGeometry(QtCore.QRect(20, 490, 246, 81))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.countriesButton = QtWidgets.QPushButton(self.centralwidget)
        self.countriesButton.clicked.connect(self.country_click)
        self.countriesButton.setGeometry(QtCore.QRect(540, 490, 246, 81))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(18)
        self.countriesButton.setFont(font)
        self.countriesButton.setObjectName("countriesButton")
        
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)  
        self.comboBox.setGeometry(QtCore.QRect(380, 140, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        for i in st_list:
            self.comboBox.addItem(i)
        self.comboBox.setCurrentIndex(34)
        self.comboBox.setObjectName("comboBox")
        
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.clicked.connect(self.clicked_data)
        self.pushButton_2.setGeometry(QtCore.QRect(672, 147, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.version = QtWidgets.QLabel(self.centralwidget)
        self.version.setGeometry(QtCore.QRect(20, 600, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(12)
        font.setBold(True)
        self.version.setFont(font)
        self.version.setObjectName("version")
        
        self.refresh = QtWidgets.QLabel(self.centralwidget)
        self.refresh.setGeometry(QtCore.QRect(339, 600, 441, 20))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setBold(True)
        font.setPointSize(12)
        self.refresh.setFont(font)
        self.refresh.setObjectName("refresh")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 26))
        self.menubar.setObjectName("menubar")
        
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        index=int(self.comboBox.currentIndex())
        state_info=data['data']['regional'][index]
        cc3=state_info['totalConfirmed']
        cci3=state_info['confirmedCasesIndian']
        ccf3=state_info['confirmedCasesForeign']
        recv3=state_info['discharged']
        dead3=state_info['deaths']
        active3=cc3-(recv3+dead3)
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "COVID-19 Tracker By Avilash Ghosh"))
        self.TITLE.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic; color:#ffffff;\">COVID-19 Tracker By Avilash</span></p></body></html>"))
        self.TITLE2.setText(_translate("MainWindow", "<html><head/><body><p>Select a State:</p></body></html>"))
        self.confirmedcases.setText(_translate("MainWindow", "Confirmed Cases: "))
        self.activecases.setText(_translate("MainWindow", "Active Cases: "))
        self.indianorigin.setText(_translate("MainWindow", "Indian Origin:"))
        self.nonindianorigin.setText(_translate("MainWindow", "Non-Indian Origin:"))
        self.recovered.setText(_translate("MainWindow", "Recovered Cases: "))
        self.deaths.setText(_translate("MainWindow", "Deaths: "))
        self.confirmedcasesdata.setText(str(cc3))
        self.indianorigindata.setText(str(cci3))
        self.recovereddata.setText(str(recv3))
        self.activecasesdata.setText(str(active3))
        self.nonindianorigindata.setText(str(ccf3))
        self.deathsdata.setText(str(dead3))
        self.unofficialsrcs.setText(_translate("MainWindow", "Data from \nCovid19.org"))
        self.pushButton.setText(_translate("MainWindow", "Data from \nGovt of India"))
        self.pushButton_2.setText(_translate("MainWindow", "Generate"))
        self.version.setText(_translate("MainWindow", "Version: 1.4"))
        self.refresh.setText("Last Refreshed on: "+str(data['lastRefreshed']))
        self.countriesButton.setText("Data of\nOther Countries")

    def clicked_data(self):
        index=int(self.comboBox.currentIndex())
        state_info=data['data']['regional'][index]
        cc3=state_info['totalConfirmed']
        cci3=state_info['confirmedCasesIndian']
        ccf3=state_info['confirmedCasesForeign']
        recv3=state_info['discharged']
        dead3=state_info['deaths']
        active3=cc3-(recv3+dead3)
        self.confirmedcasesdata.setText(str(cc3))
        self.indianorigindata.setText(str(cci3))
        self.recovereddata.setText(str(recv3))
        self.activecasesdata.setText(str(active3))
        self.nonindianorigindata.setText(str(ccf3))
        self.deathsdata.setText(str(dead3))

    def unoff_click_st(self):
        StateWindow.close()
        UnoffMainWindow.show()

    def off_click_st(self):
        StateWindow.close()
        OffMainWindow.show()

    def country_click(self):
        StateWindow.close()
        CountryWindow.show()

class Ui_CountriesMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 648)
        MainWindow.setMinimumSize(QtCore.QSize(801, 648))
        MainWindow.setMaximumSize(QtCore.QSize(801, 648))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TITLE = QtWidgets.QLabel(self.centralwidget)
        self.TITLE.setGeometry(QtCore.QRect(0, -10, 801, 111))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(38)
        self.TITLE.setFont(font)
        self.TITLE.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.TITLE.setObjectName("TITLE")
        
        self.TITLE2 = QtWidgets.QLabel(self.centralwidget)
        self.TITLE2.setGeometry(QtCore.QRect(10, 130, 341, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(26)
        self.TITLE2.setFont(font)
        self.TITLE2.setObjectName("TITLE2")
        
        self.countryname = QtWidgets.QLabel(self.centralwidget)
        self.countryname.setGeometry(QtCore.QRect(250, 240, 341, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(26)
        self.countryname.setFont(font)
        self.countryname.setObjectName("countryname")
        self.countryname.setAlignment(QtCore.Qt.AlignCenter)

        self.confirmedcases = QtWidgets.QLabel(self.centralwidget)
        self.confirmedcases.setGeometry(QtCore.QRect(30, 330, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.confirmedcases.setFont(font)
        self.confirmedcases.setObjectName("confirmedcases")
        
        self.activecases = QtWidgets.QLabel(self.centralwidget)
        self.activecases.setGeometry(QtCore.QRect(430, 330, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.activecases.setFont(font)
        self.activecases.setObjectName("activecases")
        
        self.recovered = QtWidgets.QLabel(self.centralwidget)
        self.recovered.setGeometry(QtCore.QRect(30, 410, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.recovered.setFont(font)
        self.recovered.setObjectName("recovered")
        
        self.deaths = QtWidgets.QLabel(self.centralwidget)
        self.deaths.setGeometry(QtCore.QRect(420, 410, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.deaths.setFont(font)
        self.deaths.setObjectName("deaths")
        
        self.confirmedcasesdata = QtWidgets.QLabel(self.centralwidget)
        self.confirmedcasesdata.setGeometry(QtCore.QRect(270, 350, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.confirmedcasesdata.setFont(font)
        self.confirmedcasesdata.setFrameShape(QtWidgets.QFrame.Box)
        self.confirmedcasesdata.setAlignment(QtCore.Qt.AlignCenter)
        self.confirmedcasesdata.setObjectName("confirmedcasesdata")
        
        self.recovereddata = QtWidgets.QLabel(self.centralwidget)
        self.recovereddata.setGeometry(QtCore.QRect(270, 430, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recovereddata.setFont(font)
        self.recovereddata.setFrameShape(QtWidgets.QFrame.Box)
        self.recovereddata.setAlignment(QtCore.Qt.AlignCenter)
        self.recovereddata.setObjectName("recovereddata")
        
        self.activecasesdata = QtWidgets.QLabel(self.centralwidget)
        self.activecasesdata.setGeometry(QtCore.QRect(630, 350, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.activecasesdata.setFont(font)
        self.activecasesdata.setFrameShape(QtWidgets.QFrame.Box)
        self.activecasesdata.setAlignment(QtCore.Qt.AlignCenter)
        self.activecasesdata.setObjectName("activecasesdata")
        
        self.deathsdata = QtWidgets.QLabel(self.centralwidget)
        self.deathsdata.setGeometry(QtCore.QRect(550, 430, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.deathsdata.setFont(font)
        self.deathsdata.setFrameShape(QtWidgets.QFrame.Box)
        self.deathsdata.setAlignment(QtCore.Qt.AlignCenter)
        self.deathsdata.setObjectName("deathsdata")
        
        self.unofficialsrcs = QtWidgets.QPushButton(self.centralwidget)
        self.unofficialsrcs.clicked.connect(self.unoff_click_st)
        self.unofficialsrcs.setGeometry(QtCore.QRect(276, 490, 246, 81))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(16)
        self.unofficialsrcs.setFont(font)
        self.unofficialsrcs.setDefault(False)
        self.unofficialsrcs.setObjectName("unofficialsrcs")
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.clicked.connect(self.off_click_st)
        self.pushButton.setGeometry(QtCore.QRect(20, 490, 246, 81))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.countriesButton = QtWidgets.QPushButton(self.centralwidget)
        self.countriesButton.clicked.connect(self.state_click)
        self.countriesButton.setGeometry(QtCore.QRect(540, 490, 246, 81))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(18)
        self.countriesButton.setFont(font)
        self.countriesButton.setObjectName("countriesButton")
        
        self.CountryInput = QtWidgets.QLineEdit(self.centralwidget)
        self.CountryInput.setGeometry(QtCore.QRect(380, 140, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(18)
        self.CountryInput.setFont(font)
        self.CountryInput.setAlignment(QtCore.Qt.AlignCenter)
        self.CountryInput.setObjectName("CountryInput")
        
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.clicked.connect(self.clicked_data)
        self.pushButton_2.setGeometry(QtCore.QRect(672, 147, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.version = QtWidgets.QLabel(self.centralwidget)
        self.version.setGeometry(QtCore.QRect(20, 600, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setPointSize(12)
        font.setBold(True)
        self.version.setFont(font)
        self.version.setObjectName("version")
        
        self.refresh = QtWidgets.QLabel(self.centralwidget)
        self.refresh.setGeometry(QtCore.QRect(339, 600, 441, 20))
        font = QtGui.QFont()
        font.setFamily("Kaushan Script")
        font.setBold(True)
        font.setPointSize(12)
        self.refresh.setFont(font)
        self.refresh.setObjectName("refresh")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 26))
        self.menubar.setObjectName("menubar")
        
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "COVID-19 Tracker By Avilash Ghosh"))
        self.TITLE.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic; color:#ffffff;\">COVID-19 Tracker By Avilash</span></p></body></html>"))
        self.TITLE2.setText(_translate("MainWindow", "<html><head/><body><p>Search a Country:</p></body></html>"))
        self.countryname.setText("<html><head/><body><p>Country Name</p></body></html>")
        self.confirmedcases.setText(_translate("MainWindow", "Confirmed Cases: "))
        self.activecases.setText(_translate("MainWindow", "Active Cases: "))
        self.recovered.setText(_translate("MainWindow", "Recovered Cases: "))
        self.deaths.setText(_translate("MainWindow", "Deaths: "))
        self.confirmedcasesdata.setText("0")
        self.recovereddata.setText("0")
        self.activecasesdata.setText("0")
        self.deathsdata.setText("0")
        self.unofficialsrcs.setText(_translate("MainWindow", "Data from \nCovid19.org"))
        self.pushButton.setText(_translate("MainWindow", "Data from \nGovt of India"))
        self.pushButton_2.setText(_translate("MainWindow", "Search"))
        self.version.setText(_translate("MainWindow", "Version: 1.4"))
        self.refresh.setText("Last Refreshed on: "+str(data['lastRefreshed']))
        self.countriesButton.setText("Data of \nIndividual States")

    def invalid_popup(self):
        popup3=QMessageBox()
        popup3.setWindowTitle("Error!")
        popup3.setText("Invalid Input!")
        popup3.setIcon(QMessageBox.Critical)
        popup3.setStandardButtons(QMessageBox.Retry)
        x=popup3.exec_()

    def clicked_data(self):
        self.url1 = "https://corona-virus-stats.herokuapp.com/api/v1/cases/countries-search?search="+self.CountryInput.text()
        response1 =requests.get(self.url1)
        parsed1=response1.text
        data1=json.loads(parsed1)
        if data1['data']['paginationMeta']['currentPageSize'] != 0:
            if self.CountryInput.text() == "India" or self.CountryInput.text() == "india":
                CountryWindow.close()
                OffMainWindow.show()
            else : 
                cdata=data1['data']['rows'][0]
                cname=cdata['country']
                self.countryname.setText("<html><head/><body><p>"+cname+"</p></body></html>")
                self.confirmedcasesdata.setText(cdata['total_cases'])
                self.recovereddata.setText(cdata['total_recovered'])
                self.activecasesdata.setText(cdata['active_cases'])
                self.deathsdata.setText(cdata['total_deaths'])
                self.refresh.setText("Last Refreshed on: "+data1['data']['last_update'])
        else:
            self.invalid_popup()

    def unoff_click_st(self):
        CountryWindow.close()
        UnoffMainWindow.show()

    def off_click_st(self):
        CountryWindow.close()
        OffMainWindow.show()

    def state_click(self):
        CountryWindow.close()
        StateWindow.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OffMainWindow = QtWidgets.QMainWindow()
    ui1 = Ui_OfficialMainWindow()
    ui1.setupUi(OffMainWindow)
    UnoffMainWindow = QtWidgets.QMainWindow()
    ui2 = Ui_UnofficialMainWindow()
    ui2.setupUi(UnoffMainWindow)
    StateWindow = QtWidgets.QMainWindow()
    ui = Ui_StateMainWindow()
    ui.setupUi(StateWindow)
    CountryWindow = QtWidgets.QMainWindow()
    ui3 = Ui_CountriesMainWindow()
    ui3.setupUi(CountryWindow)
    OffMainWindow.show()
    sys.exit(app.exec_())
